### PR TITLE
Use bytes instead of characters for hashlib

### PR DESCRIPTION
**Pull request by by**
Feeding bytes not characters to hashlib to make it compatible with newer versions (see for example https://python.readthedocs.io/fr/hack-in-language/library/hashlib.html)

### CODE REVIEW

**Comment by selsky** [comment]
Hi @by, can you submit this patch to our primary forge on
https://gitlab.com/NTPsec/ntpsec/-/merge_requests?

**Comment by by** [comment]
I'm sorry, I don't use GitLab.

**Comment by selsky** [comment]
May I apply your patch manually to the codebase?

**Comment by by** [comment]
Of course!

**Pull request closed without merging**
